#%RAML 1.0 Security Scheme
description: "Схема идентификации запросов из панели администрирования"
type: x-custom
describedBy:
  headers:
    AdminPanelUser:
      description: "Имя пользователя из панели администрирования"
      type: string
  responses:
    401:
      description: "Имя пользователя не указано"
