#%RAML 1.0 DataType
type: object
properties: 
  total:
    type: integer
    required: true
    description: "Количество существующих объектов всего."
  limit:
    type: integer
    required: true
    description: "Количество объектов на странице."
  page:
    type: integer
    required: true
    description: "Номер текущей страницы с нуля."