type: { collection: { ItemType: advertisementEntity } }
get:
  description: "Список опубликованных объявлений"
  is: [ pageable ]
  queryParameters:
    category_id:
      description: "ID категории для поиска"
      type: integer
      required: false
    city_id:
      description: "Идентификатор города"
      type: integer
      required: false
    user_id:
      description: "ID автора объявления"
      type: integer
    description:
      description: "Название/описание объявления"
      type: string
      required: false
    published_at:
      description: "Дата публикации"
      type: date-only
      required: false
post:
  description: "Создание нового объявления"
  body:
    type: advertisementDataObject
  responses:
    201:
    400:
      body:
        type: badRequestResponse
    500:
/awaiting_moderation:
  type: { collection: { ItemType: advertisementEntity } }
  get:
    securedBy: [ adminPanel ]
    is: [ pageable ]
    description: "Список объявлений, ожидающих модерации"
/{advertisementId}:
  uriParameters:
    advertisementId:
      description: "Идентификатор объявления"
      type: integer
  get:
    description: "Получение объявления по ID"
    responses:
      200:
        body:
          application/json:
            type: advertisementEntity
      404:
      500:
  put:
    description: "Редактирование объявления"
    body:
      type: advertisementDataObject
    responses:
      201:
      400:
        body:
          type: badRequestResponse
      500:
  delete:
    description: "Снятие объявления с публикации"
    responses:
      204:
      404:
      500:
  /publish:
    put:
      securedBy: [ adminPanel ]
      description: "Публикация объявления"
      responses:
        204:
        404:
        500:
  /cancel:
    put:
      securedBy: [ adminPanel ]
      description: "Отклонение объявления"
      responses:
        204:
        404:
        500:
