#%RAML 1.0
title: Avito Advertisements Service
version: v1
protocols: [ HTTP ]
baseUri: http://advertisements.service.avito.ru/api/{version}
mediaType:  application/json

securitySchemes:
  adminPanel: !include security_schemes/admin_panel.raml

traits:
  pageable: !include traits/pageable.raml

resourceTypes:
  collection: !include types/collection.raml

types:
    cityEntity: !include types/entities/city.raml
    cityDataObject: !include types/data_objects/city.raml
  #entities
  #enumerations

/categories:

/cities:
  type: { collection: { ItemType: cityEntity } }
  get:
    description: "Получить список городов"
    is: [ pageable ]
  post:
    securedBy: [ adminPanel ]
    description: "Добавить новый город"
    body:
      application/json:
        type: cityDataObject
    responses:
      201:
      400:
        body:
          type: badRequestResponse
      500:
  /{cityId}:
    uriParameters:
      cityId:
        description: "Идентификатор города"
        type: integer
    put:
      securedBy: [ adminPanel ]
      description: "Обновление города"
      body:
        application/json:
          type: cityDataObject
      responses:
        204:
        400:
          body:
            type: badRequestResponse
        404:
        500:
    delete:
      securedBy: [ adminPanel ]
      description: "Удаление города"
      responses:
        204:
        404:
        500:

/advertisements:
  /{advetisementId}:
    uriParameters:
      advetisementId:
        description: "Идентификатор объявления"
        type: integer
    /publish:
      put:
        securedBy: [ adminPanel ]
        description: "Публикация объявления"
        responses:
          204:
          404:
          500:
    /cancel:
      put:
        securedBy: [ adminPanel ]
        description: "Отклонение объявления"
        responses:
          204:
          404:
          500:

