#%RAML 1.0 DataType
type: object
properties: 
  email:
    type: string
    required: true
    description: "Email пользователя."
  password:
    type: string
    required: true
    description: "Пароль пользователя."