#%RAML 1.0 DataType
type: !include advertisement.post.raml
properties:
  viewsCount:
    type: integer
    required: true
    description: "Количество просмотров объявления, показывается на сайте"
  visitorsCount:
    type: integer
    required: true
    description: "Количество уникальных посещений объявления"
  archived:
    type: boolean
    required: true
    description: "Флаг, указывающий на то, что объявление перенесено в архив"
  published:
    type: boolean
    required: true
    description: "Флаг, показывающий, доступно ли объявление для показа пользователям на сайте"
  cancelled:
    type: boolean
    required: true
    description: "Флаг, указывающий на то, что объявление не прошло модерацию"
  create_date:
    type: date-only
    required: true
    description: "Дата создания"
  publish_date:
    type: date-only
    required: true
    description: "Дата публикации"
  canclel_date:
    type: date-only
    required: 
    description: "Дата отклонения"
  archive_date:
    type: date-only
    required: true
    description: "Дата окончания действия объявления и переноса его в архив"
