#%RAML 1.0 DataType
type: object
properties:
  isSuccess:
    type: boolean
    description: "Статус запроса"
  item:
    type: object
    properties:
      token:
        type: string
        description: "Api токен для авторизации."
      userId:
        type: integer
        description: "ID пользователя в системе."
      userType:
        type: string
        enum: [ admin, unit]
        description: "Тип пользователя в системе."
  